"""initial_schema_with_user_ids

Revision ID: b770c489ddcd
Revises: 
Create Date: 2026-03-28 23:23:23.129531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b770c489ddcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_current_schema(bind) -> None:
    from app.services.db import Base

    # Some ORM tables define overlapping explicit/implicit index names.
    # Deduplicate by index name before create_all so fresh bootstrap succeeds.
    seen_index_names = set()
    for table in Base.metadata.tables.values():
        for index in list(table.indexes):
            if index.name in seen_index_names:
                table.indexes.discard(index)
            else:
                seen_index_names.add(index.name)

    Base.metadata.create_all(bind=bind, checkfirst=True)


def _column_exists(bind, table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(column.get("name") == column_name for column in inspector.get_columns(table_name))


def _index_exists(bind, table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(bind)
    return any(index.get("name") == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    core_tables = {"users", "orders", "positions", "predictions", "trade_logs"}

    # Fresh/incomplete database bootstrap: create the current model schema directly.
    if not existing_tables or not core_tables.issubset(existing_tables):
        _create_current_schema(bind)
        return

    # Legacy transforms below require order_states to exist.
    # If it's missing, schema is already on a newer baseline and this revision is a no-op.
    if "order_states" not in existing_tables:
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_states', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('orders', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'reason',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('orders', 'error',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_timestamp'), 'orders', ['timestamp'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index('ix_orders_user_symbol', 'orders', ['user_id', 'symbol'], unique=False)
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    if not _column_exists(bind, 'positions', 'id'):
        op.add_column('positions', sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
    if bind.dialect.name == 'postgresql':
        op.execute(sa.text("CREATE SEQUENCE IF NOT EXISTS positions_id_seq"))
        op.execute(sa.text("UPDATE positions SET id = nextval('positions_id_seq') WHERE id IS NULL"))
        op.execute(sa.text("ALTER TABLE positions ALTER COLUMN id SET DEFAULT nextval('positions_id_seq')"))
    else:
        op.execute(sa.text("UPDATE positions SET id = 0 WHERE id IS NULL"))
    op.alter_column('positions', 'id',
               existing_type=sa.Integer(),
               nullable=False)
    op.add_column('positions', sa.Column('user_id', sa.Integer(), nullable=True))
    if not _column_exists(bind, 'positions', 'mode'):
        op.add_column('positions', sa.Column('mode', sa.String(length=10), nullable=True))
    op.execute(sa.text("UPDATE positions SET mode = 'paper' WHERE mode IS NULL"))
    op.alter_column('positions', 'mode',
               existing_type=sa.String(length=10),
               nullable=False)
    if not _column_exists(bind, 'positions', 'opened_at'):
        op.add_column('positions', sa.Column('opened_at', sa.DateTime(), nullable=True))
    if _column_exists(bind, 'positions', 'timestamp'):
        op.execute(sa.text(
            "UPDATE positions SET opened_at = COALESCE(opened_at, timestamp, CURRENT_TIMESTAMP) WHERE opened_at IS NULL"
        ))
    else:
        op.execute(sa.text("UPDATE positions SET opened_at = COALESCE(opened_at, CURRENT_TIMESTAMP) WHERE opened_at IS NULL"))
    op.alter_column('positions', 'opened_at',
               existing_type=sa.DateTime(),
               nullable=False)
    op.alter_column('positions', 'stop_loss',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('positions', 'target',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index('ix_positions_user_id', 'positions', ['user_id'], unique=False)
    op.create_unique_constraint('uq_position_user_symbol', 'positions', ['user_id', 'symbol'])
    op.create_foreign_key(None, 'positions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('positions', 'timestamp')
    op.add_column('predictions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('predictions', 'horizon',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('predictions', 'predicted_price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('predictions', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('predictions', 'explanation',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('trade_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('trade_logs', 'order_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('trade_logs', 'event',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('trade_logs', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('trade_logs', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade_logs', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('trade_logs', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade_logs', 'reason',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('trade_logs', 'mode',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('trade_logs', 'error',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('trade_logs', 'extra',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index('ix_trade_logs_user_id', 'trade_logs', ['user_id'], unique=False)
    op.create_index('ix_trade_logs_user_symbol', 'trade_logs', ['user_id', 'symbol'], unique=False)
    op.create_index('ix_trade_logs_user_timestamp', 'trade_logs', ['user_id', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'trade_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    if not _column_exists(bind, 'users', 'email'):
        op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))

    if not _column_exists(bind, 'users', 'is_active'):
        op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE users SET is_active = TRUE WHERE is_active IS NULL"))
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               nullable=False)

    if not _column_exists(bind, 'users', 'is_verified'):
        op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE users SET is_verified = FALSE WHERE is_verified IS NULL"))
    op.alter_column('users', 'is_verified',
               existing_type=sa.Boolean(),
               nullable=False)

    if not _column_exists(bind, 'users', 'starting_capital'):
        op.add_column('users', sa.Column('starting_capital', sa.Float(), nullable=True))
    op.execute(sa.text("UPDATE users SET starting_capital = 100000.0 WHERE starting_capital IS NULL"))
    op.alter_column('users', 'starting_capital',
               existing_type=sa.Float(),
               nullable=False)

    if not _column_exists(bind, 'users', 'trading_mode'):
        op.add_column('users', sa.Column('trading_mode', sa.String(length=10), nullable=True))
    op.execute(sa.text("UPDATE users SET trading_mode = 'PAPER' WHERE trading_mode IS NULL"))
    op.alter_column('users', 'trading_mode',
               existing_type=sa.String(length=10),
               nullable=False)

    if not _column_exists(bind, 'users', 'refresh_token_hash'):
        op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=255), nullable=True))

    if not _column_exists(bind, 'users', 'updated_at'):
        op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(sa.text(
        "UPDATE users SET updated_at = COALESCE(updated_at, created_at, CURRENT_TIMESTAMP) WHERE updated_at IS NULL"
    ))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               nullable=False)

    users_email_index = op.f('ix_users_email')
    if not _index_exists(bind, 'users', users_email_index):
        op.create_index(users_email_index, 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'refresh_token_hash')
    op.drop_column('users', 'trading_mode')
    op.drop_column('users', 'starting_capital')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'trade_logs', type_='foreignkey')
    op.drop_index('ix_trade_logs_user_timestamp', table_name='trade_logs')
    op.drop_index('ix_trade_logs_user_symbol', table_name='trade_logs')
    op.drop_index('ix_trade_logs_user_id', table_name='trade_logs')
    op.alter_column('trade_logs', 'extra',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('trade_logs', 'error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('trade_logs', 'mode',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('trade_logs', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('trade_logs', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade_logs', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('trade_logs', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade_logs', 'direction',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('trade_logs', 'event',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('trade_logs', 'order_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('trade_logs', 'user_id')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.alter_column('predictions', 'explanation',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('predictions', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('predictions', 'predicted_price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('predictions', 'horizon',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('predictions', 'user_id')
    op.add_column('positions', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.execute(sa.text(
        "UPDATE positions SET timestamp = COALESCE(timestamp, opened_at, CURRENT_TIMESTAMP) WHERE timestamp IS NULL"
    ))
    op.alter_column('positions', 'timestamp',
               existing_type=sa.DateTime(),
               nullable=False)
    op.drop_constraint(None, 'positions', type_='foreignkey')
    op.drop_constraint('uq_position_user_symbol', 'positions', type_='unique')
    op.drop_index('ix_positions_user_id', table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.alter_column('positions', 'target',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('positions', 'stop_loss',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('positions', 'opened_at')
    op.drop_column('positions', 'mode')
    op.drop_column('positions', 'user_id')
    op.drop_column('positions', 'id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index('ix_orders_user_symbol', table_name='orders')
    op.drop_index('ix_orders_user_status', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_timestamp'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.alter_column('orders', 'error',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'reason',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('orders', 'confidence',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('orders', 'order_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('orders', 'user_id')
    op.alter_column('order_states', 'order_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
